* spthy-ts-mode
An Emacs major mode for editing the security protocol theory language (spthy) of
the [[https://tamarin-prover.com/][Tamarin prover]], based on its tree-sitter grammar.

The mode provides syntax highlighting, automatic indentation,
imenu integration, and more, including support for SAPIC+.

** Installation
Note that this package requires Emacs 31.1 or later compiled with tree-sitter support.

*** 1. Package installation
For example, with =use-package= and =package-vc=:
#+begin_src elisp
(use-package spthy-ts-mode
  :vc (:rev :newest :url "https://github.com/fnussbaum/spthy-ts-mode"))
#+end_src

When using Spacemacs, instead add the following to =dotspacemacs-additional-packages=:
#+begin_src elisp
(spthy-ts-mode :location (recipe :repo "fnussbaum/spthy-ts-mode" :fetcher github))
#+end_src

*** 2. Grammar installation
/Note that the package only works as intended with the exact version of the
grammar specified in/ =treesit-language-source-alist=.

After installing the package, use =M-x treesit-install-language-grammar= to
install the spthy tree-sitter grammar. This will automatically install the
required version.

After updating the package, update the grammar, too, in case the required
version has changed. This can again be done via =M-x treesit-install-language-grammar=.

In case the automatic installation does not work on your system, manually
install the grammar from
https://github.com/tamarin-prover/tamarin-prover/tree/573a43953195d83e62fdbe32fc98253031bca60f.
Make sure it takes precedence over any other version of the grammar installed on
your system by moving it into the =tree-sitter= subdirectory of
=user-emacs-directory=, or a directory specified in =treesit-extra-load-path=,
which see. The file should be named =libtree-sitter-spthy.{so|dll|dylib}=.

** Configuration
*** Indentation
See =M-x customize-group spthy-ts=. You can customize the indentation
offset, the offset of rule arrows, and the indentation style of formulas.

*** Syntax Highlighting
The package defines some customizable faces, see =M-x customize-group spthy-ts=.

The language features to be highlighted are determined by the variables
=treesit-font-lock-level= and =treesit-font-lock-feature-list=, which see. The
function =treesit-font-lock-recompute-features= offers fine-grained control: For
instance, to enable highlighting of function identifiers while disabling the
special highlighting of built-in function identifiers, add the following to your
configuration:
#+begin_src elisp
(add-hook 'spthy-ts-mode-hook
          (lambda ()
            (treesit-font-lock-recompute-features
             ;; Add the `function' feature.
             '(function)
             ;; Remove the `builtin-function' feature.
             '(builtin-function)
             'spthy)))
#+end_src

*** Smartparens
If you are using [[https://github.com/Fuco1/smartparens][smartparens]], add the
following to your configuration to enable spthy support:
#+begin_src elisp
(with-eval-after-load 'spthy-ts-mode
  (require 'smartparens-spthy))
;; If necessary:
;; (add-hook 'spthy-ts-mode-hook 'smartparens-mode)
#+end_src

*** Diagnostics and more via LSP
The [[https://github.com/tamarin-prover/vscode-tamarin/tree/master/server][LSP server from the VS Code extension]] works well with the built-in LSP
client =eglot= in Emacs.

Exemplary setup (requires npm, node.js and typescript):
#+begin_src bash
EXT_DIR=$HOME/src/vscode-tamarin
BIN=$HOME/.local/bin/tamarin-ls
git clone https://github.com/tamarin-prover/vscode-tamarin $EXT_DIR
cd $EXT_DIR
npm install
cd server
tsc --build
printf '#!/bin/bash
node %s/server/out/server.js --stdio' $EXT_DIR > $BIN
chmod +x $BIN
#+end_src
Finally, add the following to your configuration:
#+begin_src elisp
(defun +tamarin-ls-init-options (&optional server)
  (let ((dir "~/src/vscode-tamarin/server/grammar/tree-sitter-tamarin/"))
    `((SpthyParserPath . ,(expand-file-name "tree-sitter-spthy.wasm" dir))
      (SplibParserPath . ,(expand-file-name "tree-sitter-splib.wasm" dir)))))

(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '((spthy-mode spthy-ts-mode) "tamarin-ls"
                 :initializationOptions +tamarin-ls-init-options)))
#+end_src
After completing these steps, =M-x eglot= in an spthy buffer should enable the LSP functionality.

** Contributing
Feel free to report any issues, make suggestions, or open pull requests.
